### ISSUE TITLE
Add version requirements to setup.py

### ISSUE THREAD

**Issue by saraedum** [MarkCBell/flipper#5]
Currently, setup.py does not make it specific which versions of its requirements are needed. It would be great if we could be more specific there. In particular, this makes it easier to package flipper for distributions such as conda-forge.

Or maybe, any version that installs is actually good enough. Then it would be nice to mention it in setup.py.

**Comment by MarkCBell** [comment]
Python packaging recommends against pinning to specific dependency versions:
"It is not considered best practice to use install_requires to pin dependencies to specific versions, or to specify sub-dependencies (i.e. dependencies of your dependencies). This is overly-restrictive, and prevents the user from gaining the benefit of dependency upgrades." 
https://packaging.python.org/discussions/install-requires-vs-requirements/

So for each of flippers dependencies, I have just added minimal dependency version numbers, e.g. networkx>=2.0, depending on the functionality of the dependency that flipper is using.

**Comment by saraedum** [comment]
Sorry if what I wrote came over in the wrong way. These minimal requirements are exactly what I meant. Thanks a lot!
